### ISSUE TITLE
missing image

### ISSUE THREAD

**Issue by chavolla** [zohooo/quadview#1]
in the preview window it shows an error about a missing fragment.png

**Comment by zohooo** [comment]
Have a look at `C:\Users\<username>\AppData\Roaming\QuadView` folder:  is there a `fragment.log` file in it? If yes, please post the content of the file.

**Comment by chavolla** [comment]
LaTeX Warning: File `example.eps' already exists on the system.
               Not generating it from this source.

("C:\Program Files\MiKTeX 2.9\tex\latex\base\fix-cm.sty"
Package: fix-cm 2015/01/14 v1.1t fixes to LaTeX

("C:\Program Files\MiKTeX 2.9\tex\latex\base\ts1enc.def"
File: ts1enc.def 2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
)) (svjour3.cls
Document Class: svjour3 2007/05/08 v3.2 
LaTeX document class for Springer journals
("C:\Program Files\MiKTeX 2.9\tex\latex\base\fleqn.clo"
File: fleqn.clo 2015/03/31 v1.1i Standard LaTeX option (flush left equations)
\mathindent=\dimen102
Applying: [2015/01/01] Make \[ robust on input line 50.
LaTeX Info: Redefining \[ on input line 51.
Already applied: [0000/00/00] Make \[ robust on input line 62.
Applying: [2015/01/01] Make \] robust on input line 74.
LaTeX Info: Redefining \] on input line 75.
Already applied: [0000/00/00] Make \] robust on input line 83.
)
Class Springer-SVJour3 Info: extra/valid Springer sub-package (-> *.clo) 
(Springer-SVJour3)           not found in option list of \documentclass
(Springer-SVJour3)           - autoactivating "global" style.
 (svglov3.clo
File: svglov3.clo 2009/12/18 v3.2 style option for standardised journals

SVJour Class option: svglov3.clo for standardised journals
)
LaTeX Font Info:    Redeclaring math symbol \Gamma on input line 147.
LaTeX Font Info:    Redeclaring math symbol \Delta on input line 148.
LaTeX Font Info:    Redeclaring math symbol \Theta on input line 149.
LaTeX Font Info:    Redeclaring math symbol \Lambda on input line 150.
LaTeX Font Info:    Redeclaring math symbol \Xi on input line 151.
LaTeX Font Info:    Redeclaring math symbol \Pi on input line 152.
LaTeX Font Info:    Redeclaring math symbol \Sigma on input line 153.
LaTeX Font Info:    Redeclaring math symbol \Upsilon on input line 154.
LaTeX Font Info:    Redeclaring math symbol \Phi on input line 155.
LaTeX Font Info:    Redeclaring math symbol \Psi on input line 156.
LaTeX Font Info:    Redeclaring math symbol \Omega on input line 157.
\logodepth=\dimen103
\headerboxheight=\dimen104
\betweenumberspace=\dimen105
\aftertext=\dimen106
\headlineindent=\dimen107
\c@inst=\count80
\c@auth=\count81
\instindent=\dimen108
\authrun=\box26
\authorrunning=\toks14
\titrun=\box27
\titlerunning=\toks15
\combirun=\box28
\c@lastpage=\count82
\rubricwidth=\dimen109
\c@section=\count83
\c@subsection=\count84
\c@subsubsection=\count85
\c@paragraph=\count86
\c@subparagraph=\count87
\spthmsep=\dimen110
\c@theorem=\count88
\c@case=\count89
\c@conjecture=\count90
\c@corollary=\count91
\c@definition=\count92
\c@example=\count93
\c@exercise=\count94
\c@lemma=\count95
\c@note=\count96
\c@problem=\count97
\c@property=\count98
\c@proposition=\count99
\c@question=\count100
\c@solution=\count101
\c@remark=\count102
\c@figure=\count103
\c@table=\count104
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\figcapgap=\dimen111
\tabcapgap=\dimen112
\figgap=\dimen113
\bibindent=\dimen114
\@tempcntc=\count105
) ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphicx.sty"
Package: graphicx 2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)

("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\keyval.sty"
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks16
)
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphics.sty"
Package: graphics 2014/10/28 v1.0p Standard LaTeX Graphics (DPC,SPQR)

("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\trig.sty"
Package: trig 1999/03/16 v1.09 sin cos tan (DPC)
)
("C:\Program Files\MiKTeX 2.9\tex\latex\00miktex\graphics.cfg"
File: graphics.cfg 2007/01/18 v1.5 graphics configuration of teTeX/TeXLive
)
Package graphics Info: Driver file: xetex.def on input line 94.

**Comment by zohooo** [comment]
It seems that the content of `fragment.log` file is uncomplete: the beginning of the file is missing here.

And to make the problem more clear, please also post the content of `fragment.tex` file.

**Comment by chavolla** [comment]
This is XeTeX, Version 3.14159265-2.6-0.99992 (MiKTeX 2.9 64-bit) (preloaded format=xelatex 2016.8.29)  9 SEP 2016 22:14
entering extended mode
**C:/Users/chavolla.AUTH/AppData/Roaming/QuadView/fragment.tex
(C:/Users/chavolla.AUTH/AppData/Roaming/QuadView/fragment.tex
LaTeX2e <2015/01/01> patch level 2
Babel <3.9m> and hyphenation patterns for 69 languages loaded.

LaTeX Warning: File `example.eps' already exists on the system.
               Not generating it from this source.

("C:\Program Files\MiKTeX 2.9\tex\latex\base\fix-cm.sty"
Package: fix-cm 2015/01/14 v1.1t fixes to LaTeX

("C:\Program Files\MiKTeX 2.9\tex\latex\base\ts1enc.def"
File: ts1enc.def 2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
)) (svjour3.cls
Document Class: svjour3 2007/05/08 v3.2 
LaTeX document class for Springer journals
("C:\Program Files\MiKTeX 2.9\tex\latex\base\fleqn.clo"
File: fleqn.clo 2015/03/31 v1.1i Standard LaTeX option (flush left equations)
\mathindent=\dimen102
Applying: [2015/01/01] Make [ robust on input line 50.
LaTeX Info: Redefining [ on input line 51.
Already applied: [0000/00/00] Make [ robust on input line 62.
Applying: [2015/01/01] Make ] robust on input line 74.
LaTeX Info: Redefining ] on input line 75.
Already applied: [0000/00/00] Make ] robust on input line 83.
)
Class Springer-SVJour3 Info: extra/valid Springer sub-package (-> *.clo) 
(Springer-SVJour3)           not found in option list of \documentclass
(Springer-SVJour3)           - autoactivating "global" style.
 (svglov3.clo
File: svglov3.clo 2009/12/18 v3.2 style option for standardised journals

SVJour Class option: svglov3.clo for standardised journals
)
LaTeX Font Info:    Redeclaring math symbol \Gamma on input line 147.
LaTeX Font Info:    Redeclaring math symbol \Delta on input line 148.
LaTeX Font Info:    Redeclaring math symbol \Theta on input line 149.
LaTeX Font Info:    Redeclaring math symbol \Lambda on input line 150.
LaTeX Font Info:    Redeclaring math symbol \Xi on input line 151.
LaTeX Font Info:    Redeclaring math symbol \Pi on input line 152.
LaTeX Font Info:    Redeclaring math symbol \Sigma on input line 153.
LaTeX Font Info:    Redeclaring math symbol \Upsilon on input line 154.
LaTeX Font Info:    Redeclaring math symbol \Phi on input line 155.
LaTeX Font Info:    Redeclaring math symbol \Psi on input line 156.
LaTeX Font Info:    Redeclaring math symbol \Omega on input line 157.
\logodepth=\dimen103
\headerboxheight=\dimen104
\betweenumberspace=\dimen105
\aftertext=\dimen106
\headlineindent=\dimen107
\c@inst=\count80
\c@auth=\count81
\instindent=\dimen108
\authrun=\box26
\authorrunning=\toks14
\titrun=\box27
\titlerunning=\toks15
\combirun=\box28
\c@lastpage=\count82
\rubricwidth=\dimen109
\c@section=\count83
\c@subsection=\count84
\c@subsubsection=\count85
\c@paragraph=\count86
\c@subparagraph=\count87
\spthmsep=\dimen110
\c@theorem=\count88
\c@case=\count89
\c@conjecture=\count90
\c@corollary=\count91
\c@definition=\count92
\c@example=\count93
\c@exercise=\count94
\c@lemma=\count95
\c@note=\count96
\c@problem=\count97
\c@property=\count98
\c@proposition=\count99
\c@question=\count100
\c@solution=\count101
\c@remark=\count102
\c@figure=\count103
\c@table=\count104
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\figcapgap=\dimen111
\tabcapgap=\dimen112
\figgap=\dimen113
\bibindent=\dimen114
\@tempcntc=\count105
) ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphicx.sty"
Package: graphicx 2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)

("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\keyval.sty"
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks16
)
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphics.sty"
Package: graphics 2014/10/28 v1.0p Standard LaTeX Graphics (DPC,SPQR)

("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\trig.sty"
Package: trig 1999/03/16 v1.09 sin cos tan (DPC)
)
("C:\Program Files\MiKTeX 2.9\tex\latex\00miktex\graphics.cfg"
File: graphics.cfg 2007/01/18 v1.5 graphics configuration of teTeX/TeXLive
)
Package graphics Info: Driver file: xetex.def on input line 94.

**Comment by zohooo** [comment]
To make the problem more clear, please also post the content of `fragment.tex` file.

**Comment by chavolla** [comment]
\PassOptionsToClass{handout}{beamer}

%%%%%%%%%%%%%%%%%%%%%%% file template.tex %%%%%%%%%%%%%%%%%%%%%%%%%
%
% This is a general template file for the LaTeX package SVJour3
% for Springer journals.          Springer Heidelberg 2010/09/16
%
% Copy it to a new file with a new name and use it as the basis
% for your article. Delete % signs as needed.
%
% This template includes a few options for different layouts and
% content for various journals. Please consult a previous issue of
% your journal as needed.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% First comes an example EPS file -- just ignore it and
% proceed on the \documentclass line
% your LaTeX will extract the file if required
\begin{filecontents_}{example.eps}
%!PS-Adobe-3.0 EPSF-3.0
%%BoundingBox: 19 19 221 221
%%CreationDate: Mon Sep 29 1997
%%Creator: programmed by hand (JK)
%%EndComments
gsave
newpath
  20 20 moveto
  20 220 lineto
  220 220 lineto
  220 20 lineto
closepath
2 setlinewidth
gsave
  .4 setgray fill
grestore
stroke
grestore
\end{filecontents_}
%
\RequirePackage{fix-cm}
%
%\documentclass{svjour3}                     % onecolumn (standard format)
%\documentclass[smallcondensed]{svjour3}     % onecolumn (ditto)
%\documentclass[smallextended]{svjour3}       % onecolumn (second format)
\documentclass[twocolumn]{svjour3}          % twocolumn
%
\smartqed  % flush right qed marks, e.g. at end of proof
%
\usepackage{graphicx}
\usepackage{epstopdf}
\usepackage[noadjust]{cite}

\renewcommand{\citedash}{--}
%
% \usepackage{mathptmx}      % use Times fonts if available on your TeX system
%
% insert here the call for the packages your document requires
%\usepackage{latexsym}
% etc.
%
% please place your own definitions here and don't use \def but
% \newcommand{}{}
%
% Insert the name of "your journal" with
% \journalname{myjournal}
%

\makeatletter
\@ifclassloaded{beamer}{}{
  \usepackage[active,tightpage]{preview}
  \setlength{\PreviewBorder}{8pt}
  \AtBeginDocument{\begin{preview}}
  \AtEndDocument{\end{preview}}
  \pagestyle{empty}
}
\makeatother
\begin{document}

\begin{itemize}
  \item HS filtering is susceptible to low V. It can produce false positive values, assigning black and dark gray colors to a certain Hue tone.
  \item HV filtering is susceptible to low S. It can produce false positives assigning gray colors to a specific incorrect Hue.
\end{itemize}

The test consists in the comparison of the three color spaces in order to contrast the filtering process among the selected options. The chosen colors are the three primary additive tones (red, green and blue).

\end{document}

**Comment by zohooo** [comment]
There is no problem with the tex file in my machine.

![issue1](https://cloud.githubusercontent.com/assets/1684992/18409245/57e16fdc-7775-11e6-835e-4297517e20a8.png)

**Comment by zohooo** [comment]
Maybe you could change the tex engine from `xelatex` to `pdflatex` by right-clicking the QuadView window.

**Comment by zohooo** [comment]
You need to install `preview` package before using QuadView. Or you will not get the preview images.

**Comment by chavolla** [comment]
I found the problem. The issue is related to a latex class is used in the document. This class is in the same folder as the document (a cls and a clo files). The fragment docuement copies the header where this  class is referred (\documentclass[twocolumn]{svjour3} ), but the latex class files are not copied. So when the pdf enginge tries to create the preview docuement, it fails as the latex class is not found. Removing the reference to the class removes the error
