### ISSUE TITLE
Problem dealing with path containing spaces

### ISSUE THREAD

**Issue by ZheruQiu** [zohooo/quadview#2]
My Windows account name contains a space, so the path to fragment folder
(eg. C:\Users\Zheru Qiu\AppData\Roaming\QuadView) contains a space in it,
This lead to problems when calling mudraw.

I suggest these lines in the Lua code be changed
`local cmd = "mudraw -r " .. tostring(resolution) .. " -o " .. "\"" .. pngname .. "\" \"" .. pdfname .. "\" 1"`
`switch = "-interaction=nonstopmode -output-directory=\"" .. datapath .. "\""`
to escape the space in the command argument.

**Comment by zohooo** [comment]
Fixed. You may download the latest release of version 0.6.
