### ISSUE TITLE
there is nothing in the windows of the QuadView

### ISSUE THREAD

**Issue by thingsc** [zohooo/quadview#4]
I have installed the QuadView as the guide says, but there is nothing in the view windows??? 
How can I fix it ?
I think it may be the problem of my TeX path, I have changed the default path to another absolute path, dose it matter ?
there is my configuration : http://osxcpovqx.bkt.clouddn.com/winedt%20configuration.png
should I offer other materials for this issue to be done?

**Comment by zohooo** [comment]
Have a look at `C:\Users\<username>\AppData\Roaming\QuadView` folder, then upload `fragment.log` and `fragment.tex` files

**Comment by fewww** [comment]
How can I use Quadview with WinEdt 5.5? Thank you.
